{
 "title": "Fraud Platform Overview",
 "tags": [
  "fraud",
  "data-engineering"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Scored Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_transactions_total", "legendFormat": "Total Transactions" }
   ]
  },
  {
   "title": "Declined Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "fraud_declined_total", "legendFormat": "Declined" }
   ]
  },
  {
   "title": "PostgreSQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"payment_scoring\"}",
     "legendFormat": "DB Connections"
    }
   ]
  }
 ]
}